from django.urls import re_path

from .views import (
    about,
    activate_user,
    add_new_form,
    add_user,
    checklist_order,
    delete_form_element,
    delete_submission_checklist,
    edit_form,
    edit_form_preparation,
    edit_setting,
    edit_submission_checklist,
    flush_cache,
    form_active,
    group,
    group_delete,
    group_members,
    group_members_assign,
    group_members_order,
    groups,
    groups_order,
    inactive_users,
    index,
    key_help,
    list_forms,
    manager_membership_delete,
    merge_users,
    preview_form,
    reorder_form,
    role,
    role_action,
    roles,
    select_merge,
    send_series,
    series,
    series_add,
    series_delete,
    series_edit,
    series_submission_add,
    series_submission_remove,
    settings_index,
    submission_checklist,
    user_edit,
    users,
)


urlpatterns = [
    re_path(  # New Submissions.
        r'^$',
        index,
        name='manager_index'
    ),
    re_path(
        r'^about/$',
        about,
        name='manager_about'
    ),
    re_path(  # Group Management.
        r'^groups/$',
        groups,
        name='manager_groups'
    ),
    re_path(
        r'^groups/order/$',
        groups_order,
        name='manager_groups_order'
    ),
    re_path(
        r'^groups/add/$',
        group,
        name='manager_group_add'
    ),
    re_path(
        r'^groups/(?P<group_id>\d+)/edit/$',
        group,
        name='manager_group_edit'
    ),
    re_path(
        r'^groups/(?P<group_id>\d+)/delete/$',
        group_delete,
        name='manager_group_delete'
    ),
    re_path(
        r'^groups/(?P<group_id>\d+)/members/$',
        group_members,
        name='manager_group_members'
    ),
    re_path(
        r'^groups/(?P<group_id>\d+)/members/user/(?P<user_id>\d+)/assign/$',
        group_members_assign,
        name='group_members_assign'
    ),
    re_path(
        r'^groups/(?P<group_id>\d+)/members/order$',
        group_members_order,
        name='group_members_order'
    ),
    re_path(
        r'^groups/(?P<group_id>\d+)/members/(?P<member_id>\d+)/delete$',
        manager_membership_delete,
        name='manager_membership_delete'
    ),
    re_path(  # Role Management.
        r'^roles/$',
        roles,
        name='manager_roles'
    ),
    re_path(
        r'^roles/(?P<slug>[-\w.]+)/$',
        role,
        name='manager_role'
    ),
    re_path(
        r'^roles/(?P<slug>[-\w.]+)/user/(?P<user_id>\d+)/(?P<action>[-\w.]+)/$',
        role_action,
        name='manager_role_action'
    ),
    re_path(  # Settings Management.
        r'^settings/$',
        settings_index,
        name='settings_index'
    ),
    re_path(
        r'^settings/group/(?P<setting_group>[-\w.]+)/setting/'
        r'(?P<setting_name>[-\w.]+)/$',
        edit_setting,
        name='edit_setting'
    ),
    re_path(  # Submission checklist.
        r'^submission/checklist/$',
        submission_checklist,
        name='submission_checklist'
    ),
    re_path(
        r'^submission/checklist/edit/(?P<item_id>\d+)/$',
        edit_submission_checklist,
        name='edit_submission_checklist'
    ),
    re_path(
        r'^submission/checklist/delete/(?P<item_id>\d+)/$',
        delete_submission_checklist,
        name='delete_submission_checklist'
    ),
    re_path(
        r'^submission/checklist/order/$',
        checklist_order,
        name='checklist_order'
    ),
    re_path(  # Series Management.
        r'^series/$',
        series,
        name='series'
    ),
    re_path(
        r'^series/add/$',
        series_add,
        name='series_add'
    ),
    re_path(
        r'^series/delete/(?P<series_id>\d+)/$',
        series_delete,
        name='series_delete'
    ),
    re_path(
        r'^series/(?P<series_id>\d+)/send/$',
        send_series,
        name='series_send_series'
    ),
    re_path(
        r'^series/(?P<series_id>\d+)/edit/$',
        series_edit,
        name='series_edit'
    ),
    re_path(
        r'^series/submission/(?P<submission_id>\d+)/series/add/'
        r'(?P<series_id>\d+)/$',
        series_submission_add,
        name='series_submission_add'
    ),
    re_path(
        r'^series/submission/(?P<submission_id>\d+)/series/remove/$',
        series_submission_remove,
        name='series_submission_remove'
    ),
    re_path(  # Cache.
        r'^cache/flush/$',
        flush_cache,
        name='manager_flush_cache'
    ),
    re_path(  # Users.
        r'^user/$',
        users,
        name='manager_users'
    ),
    re_path(
        r'^user/inactive/$',
        inactive_users,
        name='manager_inactive_users'
    ),
    re_path(
        r'^user/inactive/(?P<user_id>\d+)/activate/$',
        activate_user,
        name='manager_activate_user'
    ),
    re_path(
        r'^user/add/$',
        add_user,
        name='add_user'
    ),
    re_path(
        r'^user/(?P<user_id>\d+)/edit/$',
        user_edit,
        name='user_edit'
    ),
    re_path(
        r'^user/(?P<user_id>\d+)/edit/select_merge/$',
        select_merge,
        name='select_merge'
    ),
    re_path(
        r'^user/(?P<user_id>\d+)/edit/merge_users/(?P<secondary_user_id>\d+)/$',
        merge_users,
        name='merge_users'
    ),
    re_path(  # Key help.
        r'^key_help/$',
        key_help,
        name='manager_key_help'
    ),
    re_path(  # Forms.
        r'^forms/add/(?P<form_type>[-\w.]+)/$',
        add_new_form,
        name='manager_add_new_form'
    ),
    re_path(
        r'^forms/(?P<form_type>[-\w.]+)/(?P<form_id>\d+)/$',
        edit_form,
        name='manager_edit_form'
    ),
    re_path(
        r'^forms/active/(?P<form_type>[-\w.]+)/(?P<form_id>\d+)/$',
        form_active,
        name='manager_form_active'
    ),
    re_path(
        r'^forms/prepare/(?P<form_type>[-\w.]+)/(?P<form_id>\d+)/$',
        edit_form_preparation,
        name='manager_edit_form_preparation'
    ),
    re_path(
        r'^forms/(?P<form_type>[-\w.]+)/(?P<form_id>\d+)/switch/'
        r'(?P<field_1_id>\d+)/(?P<field_2_id>\d+)$',
        reorder_form,
        name='manager_reorder_form'
    ),
    re_path(
        r'^forms/(?P<form_type>[-\w.]+)/(?P<form_id>\d+)/element/'
        r'(?P<relation_id>\d+)/$',
        edit_form,
        name='manager_edit_form_element'
    ),
    re_path(
        r'^forms/(?P<form_type>[-\w.]+)/(?P<form_id>\d+)/element/'
        r'(?P<relation_id>\d+)/delete/$',
        delete_form_element,
        name='manager_delete_form_element'
    ),
    re_path(
        r'^forms/(?P<form_type>[-\w.]+)/(?P<form_id>\d+)/preview/$',
        preview_form,
        name='manager_preview_form'
    ),
    re_path(
        r'^forms/(?P<form_type>[-\w.]+)/$',
        list_forms,
        name='manager_forms'
    ),
]
