from django.urls import re_path

from .views import (
   author_contract_signoff,
   author_dashboard,
   author_production,
   author_submission,
   author_view_typesetter,
   copyedit_review,
   editing,
   proposal_author_contract_signoff,
   review,
   revise_file,
   revision,
   RevisionCompletionEmail,
   revision_new_file,
   status,
   tasks,
   typeset_review,
   view_chapter,
   view_chapter_format,
   view_copyedit,
   view_index,
   view_review_assignment,
   view_review_round,
   view_revisions,
)

urlpatterns = [
   re_path(
      r'dashboard/$',
      author_dashboard,
      name='author_dashboard'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/$',
      author_submission,
      name='author_submission'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/status/$',
      status,
      name='status'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/tasks/$',
      tasks,
      name='tasks'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/review/$',
      review,
      name='review'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/'
      r'review/revisions/(?P<revision_id>\d+)/$',
      view_revisions,
      name='view_revisions'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/'
      r'review/round/(?P<round_id>\d+)/$',
      view_review_round,
      name='view_review_round'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/'
      r'review/round/(?P<round_id>\d+)/assignment/(?P<review_id>\d+)/$',
      view_review_assignment,
      name='view_review_assignment'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/$',
      editing,
      name='editing'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'view/copyeditor/(?P<copyedit_id>\d+)/$',
      view_copyedit,
      name='author_view_copyedit'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'view/indexer/(?P<index_id>\d+)/$',
      view_index,
      name='author_view_index'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'copyedit/(?P<copyedit_id>\d+)/$',
      copyedit_review,
      name='copyedit_review'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'typeset/(?P<typeset_id>\d+)/$',
      typeset_review,
      name='typeset_review'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/$',
      author_production,
      name='author_production'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/'
      r'view/typesetter/(?P<typeset_id>\d+)$',
      author_view_typesetter,
      name='author_view_typesetter'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/$',
      revision,
      name='author_revision'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/completion_email/$',
      RevisionCompletionEmail.as_view(),
      name='author_revision_completion_email'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/update_file/(?P<file_id>\d+)/$',
      revise_file,
      name='revise_file'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/new/(?P<file_type>[-\w]+)/file/$',
      revision_new_file,
      name='revision_new_file'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/contract/'
      r'(?P<contract_id>\d+)/signoff/$',
      author_contract_signoff,
      name='author_contract_signoff'
   ),
   re_path(
      r'^proposal/(?P<proposal_id>\d+)/contract/(?P<contract_id>\d+)/signoff/$',
      proposal_author_contract_signoff,
      name='proposal_author_contract_signoff'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/'
      r'chapter/(?P<chapter_id>\d+)/view/$',
      view_chapter,
      name='author_view_chapter'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/'
      r'chapter/(?P<chapter_id>\d+)/view/format/(?P<format_id>\d+)/$',
      view_chapter_format,
      name='author_view_chapter_format'
   ),
]
