# Generated by Django 2.1.2 on 2018-10-18 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ref', models.CharField(help_text='for proposals: press_code-proposal eg. sup-proposal', max_length=50)),
                ('intro_text', models.TextField(help_text='Accepts HTML. Para elements should be wrapped in paragraph tags or they will not have fonts.', max_length=1000)),
                ('completion_text', models.TextField(help_text='Accepts HTML. Para elements should be wrapped in paragraph tags or they will not have fonts.', max_length=1000)),
                ('in_edit', models.BooleanField(default=False, help_text='True if form is in edit stage.')),
                ('active', models.BooleanField(default=True, help_text='If set to False, will be hidden from use in proposal workflow.')),
            ],
        ),
        migrations.CreateModel(
            name='FormElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('choices', models.CharField(blank=True, help_text='Separate choices with the bar | character.', max_length=500, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text Field'), ('textarea', 'Text Area'), ('check', 'Check Box'), ('select', 'Select'), ('email', 'Email'), ('upload', 'Upload'), ('date', 'Date')], max_length=100)),
                ('required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FormElementsRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(choices=[('col-md-4', 'third'), ('col-md-6', 'half'), ('col-md-12', 'full')], max_length=20)),
                ('help_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.FormElement')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Form')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FormResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Form')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='form_fields',
            field=models.ManyToManyField(blank=True, related_name='form_fields', to='review.FormElementsRelationship'),
        ),
    ]
