# Generated by Django 2.1.2 on 2018-10-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_from_editor', models.TextField(help_text='These notes should be as clear as possible to instruct the author on the revisions required. The notes will be displayed to the author.')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('revision_type', models.CharField(choices=[('submission', 'Submission'), ('review', 'Review')], max_length=100)),
                ('requested', models.DateField(auto_now_add=True)),
                ('due', models.DateField(blank=True, help_text='Set the date the revisions are due. The author will be reminded once before the due date and once after.', null=True)),
                ('completed', models.DateField(blank=True, null=True)),
                ('overdue_reminder', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
