# Generated by Django 2.1.2 on 2018-10-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverImageProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned', models.DateField(auto_now_add=True)),
                ('note_to_author', models.TextField(help_text='Provide some notes on the cover for the author.')),
                ('completed', models.DateField(blank=True, null=True)),
                ('note_to_editor', models.TextField(help_text='Provide some feedback to the Editor on the cover image.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='editor')),
            ],
        ),
    ]
